window.APP_CONFIG = {
  siteName: 'ARQO',
  whatsappNumber: '201007850179',
  email: 'arqo.design7070@gmail.com',
  phone: '+201007850179',
  phoneDisplay: '01007850179',
  address: 'Corniche El Maadi, Officers’ Buildings',
  projectSlug: 'modern-villa-renovation',
  navItems: [
    { label: 'Home', href: 'index.html', key: 'home' },
    { label: 'About', href: 'about.html', key: 'about' },
    { label: 'Services', href: 'services.html', key: 'services' },
    { label: 'Projects', href: 'projects.html', key: 'projects' },
    { label: 'Gallery', href: 'gallery.html', key: 'gallery' },
    { label: 'Contact', href: 'contact.html', key: 'contact' }
  ]
};

window.APP_TRANSLATIONS = {
  en: {
    home: 'Home',
    about: 'About',
    services: 'Services',
    projects: 'Projects',
    gallery: 'Gallery',
    contact: 'Contact',
    quote: 'Get a Quote',
    cta: 'Explore Projects',
    whatsapp: 'WhatsApp Us',
    language: 'AR',
    theme: 'Dark Mode',
    requestQuote: 'Request a Quote',
    ourStory: 'Our Story',
    homeHero: 'INTERIOR DESIGN & FINISHING',
    heroText: 'We transform spaces into exceptional living experiences with elevated materiality, architectural detail, and precise execution.',
    crafted: 'Crafted With Precision.',
    selectedWorks: 'Selected Works',
    architectureLed: 'Architecture-led, human-centered.',
    ourPhilosophy: 'Our Philosophy',
    philosophyP1: 'At ARQO, every line, finish, and piece is chosen with intention. We approach design as a complete experience—where circulation, light, texture, and rhythm all work together.',
    philosophyP2: 'We craft homes, villas, boutique spaces, and hospitality interiors that feel tailored to the people who live and work in them — refined without excess, warm without compromise.',
    philosophyQuote: 'One Vision. One Process. One Responsible Partner.',
    values: 'Our Values',
    valuesTitle: 'Clarity, craft, and consistency.',
    materialIntegrity: 'Material Integrity',
    materialIntegrityText: 'We specify naturally rich materials and finishes that age beautifully and perform under real life conditions.',
    precisionExecution: 'Precision Execution',
    precisionExecutionText: 'Every detail is managed with technical oversight, from design intent to final installation and finishing.',
    tailoredStyling: 'Tailored Styling',
    tailoredStylingText: 'We tailor each palette, fixture, and object to reflect the identity and rhythm of the project.',
    clientPartnership: 'Client Partnership',
    clientPartnershipText: 'We work closely with clients, consultants, and contractors to keep each decision aligned and intentional.',
    milestones: 'Milestones',
    milestonesTitle: 'Built on trust and refined execution.',
    selectedPortfolio: 'Selected Portfolio',
    whatWeDo: 'What We Do',
    ourWorkflow: 'Our Workflow',
    workflowTitle: 'One Vision. One Process. One Responsible Partner.',
    brief: 'Brief',
    briefText: 'We define goals, budget, mood, and priorities.',
    design: 'Design',
    designText: 'Layouts, material palettes, lighting studies, and design proposals.',
    build: 'Build',
    buildText: 'Procurement, detailing, supervision, and on-site coordination.',
    style: 'Style',
    styleText: 'Final furnishing, placement, and finishing touches for a complete atmosphere.',
    projectSummary: 'Project Summary',
    projectSummaryText: 'We reimagined the living experience with seamless transitions, a restrained palette, and subtle detailing that heightens comfort and calm.',
    projectGalleryIntro: 'Browse all photos from this project.',
    designHighlights: 'Design Highlights',
    designHighlightsText: 'Custom joinery, layered lighting, brushed brass accents, and curated furniture styling.',
    location: 'Location',
    scope: 'Scope',
    scopeText: 'Full interior design, material specification, finishing, and styling',
    nameLabel: 'Name',
    phoneLabel: 'Phone',
    emailLabel: 'Email',
    projectTypeLabel: 'Project Type',
    projectBriefLabel: 'Project Brief',
    projectBriefPlaceholder: 'Describe your project goals, area, and desired style.',
    namePlaceholder: 'Enter your name',
    phonePlaceholder: 'Your phone number',
    emailPlaceholder: 'name@example.com',
    messagePlaceholder: 'Tell us about your idea, timeline, and scope.',
    addressLabel: 'Address',
    whatsappLabel: 'WhatsApp',
    emailContactLabel: 'Email',
    phoneContactLabel: 'Phone',
    servicesHero: 'End-to-end interior solutions.',
    servicesIntro: 'From architecturally informed concepts to premium execution, we deliver spaces that look exceptional and function beautifully.',
    projectsHero: 'Distinctive interiors, beautifully resolved.',
    projectsIntro: 'Explore a collection of residential, hospitality, and commercial spaces shaped by calm luxury and thoughtful detailing.',
    galleryHero: 'Selected visuals from our latest work.',
    galleryIntro: 'A curated collection of interior moments, finishing details, and atmosphere-led design decisions.',
    getInTouch: 'Get In Touch',
    contactHero: 'Start your next project with us.',
    contactIntro: 'Tell us about your space, ambitions, and timeline. We’ll guide you toward a tailored design and finishing strategy.',
    startProjectTitle: 'Start Your Project',
    quoteHero: 'Request a tailored design consultation.',
    quoteIntro: 'Share your goals, timeline, and preferred style. We’ll prepare a tailored proposal for your interior project.',
    designSolutions: 'Design solutions for the way you live.',
    processTitle: 'One Vision. One Process. One Responsible Partner.',
    trusted: 'Trusted by discerning homeowners and brands.',
    begin: 'Let’s Begin',
    tellUs: 'Tell us about your next interior project.',
    ourServices: 'Our Services',
    viewAllServices: 'View all services',
    allProjects: 'All Projects',
    process: 'Our Approach',
    testimonials: 'Testimonials',
    explore: 'Explore',
    support: 'Support',
    view: 'View',
    photos: 'photos',
    previousPhoto: 'Previous photo',
    nextPhoto: 'Next photo',
    allFilter: 'All',
    residentialFilter: 'Residential',
    luxuryFilter: 'Luxury',
    hospitalityFilter: 'Hospitality',
    commercialFilter: 'Commercial',
    retailFilter: 'Retail',
    optionResidential: 'Residential',
    optionLuxuryVilla: 'Luxury Villa',
    optionCommercial: 'Commercial',
    optionHospitality: 'Hospitality',
    contactDetails: 'Contact Details',
    weLove: 'We’d love to hear from you.',
    sendMessage: 'Send Message',
    weRespond: 'We usually respond within 24 hours.',
    portfolio: 'Portfolio',
    whoWeAre: 'Who We Are',
    aboutHero: 'Designing spaces with lasting clarity.',
    aboutIntro: 'We create interiors that feel effortless, tactile, and deeply personal — balancing form, function, and permanence.',
    selectedGallery: 'Selected visuals from our latest work.',
    startProject: 'Start your next project with us.',
    requestTailored: 'Request a tailored design consultation.',
    whyChooseUs: 'Why Choose Us',
    clearProcess: 'Clear process. Refined results.',
    quoteText: 'We combine interior strategy, premium finishing, and construction oversight to turn complex ideas into finished spaces you can live in beautifully.',
    consultation: 'Consultation',
    consultationText: 'Initial brief, budget guidance, and design direction.',
    proposal: 'Proposal',
    proposalText: 'Scope, timelines, key milestones, and next steps.',
    execution: 'Execution',
    executionText: 'Procurement, site coordination, and handover support.',
    submitRequest: 'Submit Request',
    noCost: 'No-cost initial consultation.',
    startProjectLabel: 'Start your next project with us.',
    homeTitle: 'Home',
    aboutTitle: 'About',
    servicesTitle: 'Services',
    projectsTitle: 'Projects',
    galleryTitle: 'Gallery',
    contactTitle: 'Contact',
    aboutBadge: 'Design Awards',
    storyEyebrow: 'About ARQO',
    companyStoryTitle: 'Crafted With Precision.',
    companyStoryP1: 'ARQO is a specialized interior design and finishing company. We create refined spaces that balance architecture, functionality, and comfort, with every detail carefully considered.',
    companyStoryP2: 'From homes and villas to hospitality spaces, we bring together thoughtful design and precise execution to create spaces tailored to the people who use them.',
    servicesSection: 'Our Services',
    homeServicesTitle: 'Design solutions for the way you live.',
    selectedWorksTitle: 'Spaces that feel elevated from the moment you enter.',
    oneVision: 'One vision',
    oneProcess: 'One process',
    responsiblePartner: 'Responsible partner',
    processStages: 'Process stages',
    approachNeeds: 'Understand needs',
    approachNeedsText: 'We clarify your requirements and goals before the work begins.',
    approachPlanning: 'Planning',
    approachPlanningText: 'We organize the project stages and set execution priorities.',
    approachDesign: 'Design',
    approachDesignText: 'We turn your requirements into a complete, considered design.',
    approachMaterials: 'Material selection',
    approachMaterialsText: 'We choose materials suited to the design and how the space will be used.',
    approachExecution: 'Execution',
    approachExecutionText: 'We bring the design to life and coordinate work on site.',
    approachQuality: 'Quality control',
    approachQualityText: 'We review the work at each stage to ensure it meets the agreed specifications.',
    approachHandover: 'Handover',
    approachHandoverText: 'We hand over the project after a final review.',
    testimonialsTitle: 'Trusted by homeowners and brands.',
    requestConsultation: 'Request a Consultation',
    footerDescription: 'ARQO specializes in interior design and finishing, creating thoughtfully designed spaces with quality craftsmanship.',
    footerContact: 'Contact',
    footerTagline: 'One Vision. One Process. One Responsible Partner.',
    copyright: '© 2026 ARQO',
    navLabel: 'Main navigation',
    mobileNavLabel: 'Mobile navigation',
    switchLanguage: 'Switch to Arabic',
    darkMode: 'Dark mode',
    openMenu: 'Open menu',
    closeLightbox: 'Close image',
    visualAlt: 'Interior design project',
    projectImageAlt: 'Project photo',
    socialInstagram: 'Instagram',
    socialFacebook: 'Facebook',
    socialLinkedIn: 'LinkedIn',
    reviewAlt: 'Customer review',
    projectNotFound: 'Project not found.',
    browseProjects: 'Browse all projects',
    contactSuccess: 'Thank you. We will contact you within 24 hours.',
    quoteSuccess: 'Your request has been received successfully.',
    homeDocumentTitle: 'ARQO | Interior Design & Finishing',
    aboutDocumentTitle: 'About | ARQO',
    servicesDocumentTitle: 'Services | ARQO',
    projectsDocumentTitle: 'Projects | ARQO',
    galleryDocumentTitle: 'Gallery | ARQO',
    contactDocumentTitle: 'Contact | ARQO',
    quoteDocumentTitle: 'Request a Quote | ARQO',
    projectDocumentTitle: 'Project Details | ARQO',
    homeDescription: 'ARQO offers interior design and finishing services, transforming spaces with thoughtful design and precise execution.',
    aboutDescription: 'Learn about ARQO, our approach to interior design, and our commitment to quality finishing.',
    servicesDescription: 'Interior design and finishing services for residential and commercial projects.',
    projectsDescription: 'Explore interior design and finishing projects by ARQO.',
    galleryDescription: 'Explore ARQO interior design and finishing project photos.',
    contactDescription: 'Contact ARQO to discuss your interior design or finishing project.',
    quoteDescription: 'Request an interior design and finishing consultation from ARQO.',
    projectDescription: 'Explore project photos by ARQO.',
    addressValue: 'Corniche El Maadi, Officers’ Buildings',
    scrollDown: 'Scroll down'
  },
  ar: {
    home: 'الرئيسية',
    about: 'من نحن',
    services: 'الخدمات',
    projects: 'المشاريع',
    gallery: 'المعرض',
    contact: 'تواصل',
    quote: 'احصل على عرض سعر',
    cta: 'استكشف المشاريع',
    whatsapp: 'تواصل واتساب',
    language: 'EN',
    theme: 'الوضع الداكن',
    requestQuote: 'اطلب عرض سعر',
    ourStory: 'قصتنا',
    homeHero: 'تصميم داخلي وتشطيبات',
    heroText: 'نحو مساحات استثنائية تجمع بين الملمس الفاخر والتفاصيل المعمارية والتنفيذ الدقيق.',
    crafted: 'مصمم بدقة.',
    selectedWorks: 'أعمال مختارة',
    architectureLed: 'تصميم معماري يركز على الإنسان.',
    ourPhilosophy: 'فلسفتنا',
    philosophyP1: 'في أركو، نختار كل تفصيلة وتشطيب وقطعة بعناية. وننظر إلى التصميم كتجربة متكاملة تتناغم فيها الحركة والإضاءة والملمس والإيقاع.',
    philosophyP2: 'نصمم المنازل والفيلات والمساحات الراقية والمقاهي والفنادق بطريقة تناسب حياة من يعيشون ويعملون فيها — فاخرة دون مبالغة، ودافئة دون تنازل.',
    philosophyQuote: 'رؤية واحدة. نظام واحد. شريك مسؤول عن مشروعك.',
    values: 'قيمنا',
    valuesTitle: 'الوضوح، الحرفية، والاتساق.',
    materialIntegrity: 'سلامة المواد',
    materialIntegrityText: 'نختار مواد وتشطيبات فاخرة تدوم بفخامة وتتحمل الحياة اليومية.',
    precisionExecution: 'تنفيذ دقيق',
    precisionExecutionText: 'يتم إدارة كل التفاصيل تحت إشراف فني دقيق، من الفكرة إلى التركيب النهائي والتشطيب.',
    tailoredStyling: 'تنسيق مخصص',
    tailoredStylingText: 'نعدّل كل لوحة ألوان ومفروشات وتجهيزات لتعكس هوية المشروع وإيقاعه.',
    clientPartnership: 'شراكة العميل',
    clientPartnershipText: 'نعمل عن قرب مع العملاء والمصممين والجهات التنفيذية للحفاظ على تماسك كل قرار.',
    milestones: 'المعالم',
    milestonesTitle: 'بنيت على الثقة والتنفيذ الدقيق.',
    selectedPortfolio: 'ملف أعمال مختار',
    whatWeDo: 'ماذا نفعل',
    ourWorkflow: 'منهجية عملنا',
    workflowTitle: 'رؤية واحدة. نظام واحد. شريك مسؤول عن مشروعك.',
    brief: 'الموجز',
    briefText: 'نحدد الأهداف والميزانية والمزاج والأولويات.',
    design: 'التصميم',
    designText: 'تخطيط المساحات، لوحات المواد، دراسات الإضاءة، واقتراحات التصميم.',
    build: 'التنفيذ',
    buildText: 'المشتريات، التفاصيل، الإشراف، وتنسيق الموقع.',
    style: 'التنسيق',
    styleText: 'التأثيث النهائي، الترتيب، واللمسات النهائية للجو الكامل.',
    projectSummary: 'ملخص المشروع',
    projectSummaryText: 'أعدنا تصور تجربة المعيشة عبر انتقالات سلسة، لوحة ألوان متحفظة، وتفاصيل دقيقة تعزز الراحة والهدوء.',
    projectGalleryIntro: 'تصفح جميع صور هذا المشروع.',
    designHighlights: 'نقاط التصميم',
    designHighlightsText: 'نجارة مخصصة، إضاءة متعددة الطبقات، لمسات نحاسية مصقولة، وتنسيق أثاث مختار بعناية.',
    location: 'الموقع',
    scope: 'النطاق',
    scopeText: 'تصميم داخلي كامل، مواصفات المواد، التشطيب، والتنسيق',
    nameLabel: 'الاسم',
    phoneLabel: 'الهاتف',
    emailLabel: 'البريد الإلكتروني',
    projectTypeLabel: 'نوع المشروع',
    projectBriefLabel: 'ملخص المشروع',
    projectBriefPlaceholder: 'اكتب أهداف مشروعك، مساحته، ونمطه المطلوب.',
    namePlaceholder: 'أدخل اسمك',
    phonePlaceholder: 'رقم هاتفك',
    emailPlaceholder: 'name@example.com',
    messagePlaceholder: 'أخبرنا عن فكرتك، جدولك الزمني، ونطاق المشروع.',
    addressLabel: 'العنوان',
    whatsappLabel: 'واتساب',
    emailContactLabel: 'البريد الإلكتروني',
    phoneContactLabel: 'الهاتف',
    servicesHero: 'حلول داخلية متكاملة.',
    servicesIntro: 'من المفاهيم المعمارية إلى التنفيذ الفاخر، ننتج مساحات تبدو استثنائية وتعمل بشكل رائع.',
    projectsHero: 'تصميمات داخلية مميزة بتفاصيل متقنة.',
    projectsIntro: 'اكتشف مجموعة من المساحات السكنية والفندقية والتجارية المصممة بأسلوب فاخر وهادئ.',
    galleryHero: 'لقطات مختارة من أحدث أعمالنا.',
    galleryIntro: 'مجموعة مختارة من المساحات الداخلية وتفاصيل التشطيبات وقرارات التصميم المعبرة عن أجواء المكان.',
    getInTouch: 'تواصل معنا',
    contactHero: 'ابدأ مشروعك القادم معنا.',
    contactIntro: 'أخبرنا عن مساحتك وأهدافك وجدولك الزمني. سنرشدك نحو استراتيجية تصميم وتشطيب مخصصة.',
    startProjectTitle: 'ابدأ المشروع',
    quoteHero: 'اطلب استشارة تصميم مخصصة.',
    quoteIntro: 'شارك أهدافك وجدولك الزمني ونمطك المفضل. سنعد لك عرضاً مخصصاً لمشروعك الداخلي.',
    designSolutions: 'حلول تصميم تناسب أسلوب حياتك.',
    processTitle: 'رؤية واحدة. نظام واحد. شريك مسؤول عن مشروعك.',
    trusted: 'موثوق بنا من قبل أصحاب المنازل والعلامات التجارية.',
    begin: 'لنبدأ',
    tellUs: 'أخبرنا عن مشروعك القادم في التصميم الداخلي.',
    ourServices: 'خدماتنا',
    viewAllServices: 'عرض كل الخدمات',
    allProjects: 'كل المشروعات',
    process: 'منهجية عملنا',
    testimonials: 'آراء العملاء',
    explore: 'اكتشف',
    support: 'الدعم',
    view: 'عرض',
    photos: 'صور',
    previousPhoto: 'الصورة السابقة',
    nextPhoto: 'الصورة التالية',
    allFilter: 'الكل',
    residentialFilter: 'سكني',
    luxuryFilter: 'فاخر',
    hospitalityFilter: 'ضيافة',
    commercialFilter: 'تجاري',
    retailFilter: 'تجزئة',
    optionResidential: 'سكني',
    optionLuxuryVilla: 'فيلا فاخرة',
    optionCommercial: 'تجاري',
    optionHospitality: 'ضيافة',
    contactDetails: 'تفاصيل التواصل',
    weLove: 'يسعدنا سماعك.',
    sendMessage: 'إرسال الرسالة',
    weRespond: 'عادةً ما نرد خلال 24 ساعة.',
    portfolio: 'المعرض',
    whoWeAre: 'من نحن',
    aboutHero: 'تصميم مساحات بوضوح دائم.',
    aboutIntro: 'نصمم مساحات داخلية مريحة وشخصية، تجمع بين جمال الشكل والوظيفة العملية والجودة المستدامة.',
    selectedGallery: 'لقطات مختارة من أحدث أعمالنا.',
    startProject: 'ابدأ مشروعك القادم معنا.',
    requestTailored: 'اطلب استشارة تصميم مخصصة.',
    whyChooseUs: 'لماذا تختارنا',
    clearProcess: 'عملية واضحة. نتائج متقنة.',
    quoteText: 'نمزج بين استراتيجية التصميم والتشطيبات الفاخرة والإشراف على التنفيذ لتحويل الأفكار المعقدة إلى مساحات جاهزة للعيش فيها بشكل رائع.',
    consultation: 'الاستشارة',
    consultationText: 'موجز المشروع، توجيه الميزانية، واتجاه التصميم.',
    proposal: 'العرض',
    proposalText: 'النطاق، الجداول الزمنية، المعالم الرئيسية، والخطوات التالية.',
    execution: 'التنفيذ',
    executionText: 'المشتريات، تنسيق الموقع، ودعم التسليم النهائي.',
    submitRequest: 'إرسال الطلب',
    noCost: 'استشارة أولية مجانية.',
    startProjectLabel: 'ابدأ مشروعك القادم معنا.',
    homeTitle: 'الرئيسية',
    aboutTitle: 'من نحن',
    servicesTitle: 'الخدمات',
    projectsTitle: 'المشاريع',
    galleryTitle: 'المعرض',
    contactTitle: 'تواصل',
    aboutBadge: 'جوائز تصميم',
    storyEyebrow: 'عن أركو',
    companyStoryTitle: 'تصميم متقن لكل تفصيلة.',
    companyStoryP1: 'أركو شركة متخصصة في التصميم الداخلي والتشطيبات. نصمم مساحات راقية تجمع بين جمال العمارة والوظيفة والراحة، مع الاهتمام بكل تفصيلة.',
    companyStoryP2: 'من المنازل والفيلات إلى المساحات الفندقية، نجمع بين التصميم المدروس والتنفيذ الدقيق لنصنع مساحات تناسب أصحابها.',
    servicesSection: 'خدماتنا',
    homeServicesTitle: 'تصميم يناسب أسلوب حياتك.',
    selectedWorksTitle: 'مساحات تترك انطباعًا مميزًا منذ اللحظة الأولى.',
    oneVision: 'رؤية واحدة',
    oneProcess: 'نظام واحد',
    responsiblePartner: 'شريك مسؤول عن مشروعك',
    processStages: 'مراحل العمل',
    approachNeeds: 'فهم الاحتياجات',
    approachNeedsText: 'نفهم احتياجاتك وأهداف المشروع قبل بدء العمل.',
    approachPlanning: 'التخطيط',
    approachPlanningText: 'نرتب خطوات العمل ونحدد أولويات التنفيذ.',
    approachDesign: 'التصميم',
    approachDesignText: 'نحول احتياجاتك إلى تصميم متكامل ومدروس.',
    approachMaterials: 'تحديد الخامات',
    approachMaterialsText: 'نختار الخامات المناسبة للتصميم وطبيعة الاستخدام.',
    approachExecution: 'التنفيذ',
    approachExecutionText: 'ننقل التصميم إلى الواقع ونتابع الأعمال في الموقع.',
    approachQuality: 'مراقبة الجودة',
    approachQualityText: 'نراجع مراحل العمل ونتأكد من مطابقتها للمواصفات.',
    approachHandover: 'التسليم',
    approachHandoverText: 'نسلم المشروع بعد المراجعة النهائية.',
    testimonialsTitle: 'ثقة أصحاب المنازل والعلامات التجارية.',
    requestConsultation: 'اطلب استشارة',
    footerDescription: 'أركو متخصصة في التصميم الداخلي والتشطيبات، وتبتكر مساحات مدروسة بتنفيذ وحرفية عالية.',
    footerContact: 'تواصل معنا',
    footerTagline: 'رؤية واحدة. نظام واحد. شريك مسؤول عن مشروعك.',
    copyright: '© 2026 أركو',
    navLabel: 'القائمة الرئيسية',
    mobileNavLabel: 'قائمة التصفح',
    switchLanguage: 'التبديل إلى الإنجليزية',
    darkMode: 'الوضع الداكن',
    openMenu: 'فتح القائمة',
    closeLightbox: 'إغلاق الصورة',
    visualAlt: 'مشروع تصميم داخلي',
    projectImageAlt: 'صورة من المشروع',
    socialInstagram: 'إنستغرام',
    socialFacebook: 'فيسبوك',
    socialLinkedIn: 'لينكدإن',
    reviewAlt: 'تقييم أحد العملاء',
    projectNotFound: 'المشروع غير موجود.',
    browseProjects: 'تصفح جميع المشروعات',
    contactSuccess: 'شكرًا لك، سنتواصل معك خلال 24 ساعة.',
    quoteSuccess: 'تم استلام طلبك بنجاح.',
    homeDocumentTitle: 'أركو | التصميم الداخلي والتشطيبات',
    aboutDocumentTitle: 'من نحن | أركو',
    servicesDocumentTitle: 'خدماتنا | أركو',
    projectsDocumentTitle: 'مشروعاتنا | أركو',
    galleryDocumentTitle: 'معرض الأعمال | أركو',
    contactDocumentTitle: 'تواصل معنا | أركو',
    quoteDocumentTitle: 'طلب عرض سعر | أركو',
    projectDocumentTitle: 'تفاصيل المشروع | أركو',
    homeDescription: 'تقدم أركو خدمات التصميم الداخلي والتشطيبات، وتحول المساحات بتصميم مدروس وتنفيذ دقيق.',
    aboutDescription: 'تعرف على أركو ونهجنا في التصميم الداخلي والتزامنا بجودة التشطيبات.',
    servicesDescription: 'خدمات التصميم الداخلي والتشطيبات للمشروعات السكنية والتجارية.',
    projectsDescription: 'استكشف مشروعات أركو في التصميم الداخلي والتشطيبات.',
    galleryDescription: 'شاهد صور مشروعات أركو في التصميم الداخلي والتشطيبات.',
    contactDescription: 'تواصل مع أركو لمناقشة مشروعك في التصميم الداخلي أو التشطيبات.',
    quoteDescription: 'اطلب استشارة من أركو للتصميم الداخلي والتشطيبات.',
    projectDescription: 'استكشف صور مشروعات أركو.',
    addressValue: 'كورنيش المعادي، عمارات الظباط',
    scrollDown: 'انتقل لأسفل'
  }
};
